### ISSUE TITLE
Cannot get working with Inkscape 0.48 in Ubuntu 14.04

### ISSUE THREAD

**Issue by kojow7** [fablabnbg/inkscape-centerline-trace#1]
I am getting the following error whenever I click the Apply button:

```
Traceback (most recent call last):
  File "centerline-trace.py", line 81, in <module> inkex.localize()
AttributeError: 'module' object has no attribute 'localize'
```

Any ideas why?

**Comment by Moini** [comment]
Right, that was changed in version 0.91. 

You should no longer get that error if you add a # in the first position at line 81 in the centerline-trace.py file (but I - as another user, using 0.91 - can't get it to return a centerline trace).

**Comment by jnweiger** [comment]
I've fixed the inkex.localize() call. Thanks for pointing this out.
There may be more to make it run on 0.48 (untested from my side). Please reopen, if you get a next error.

**Comment by jnweiger** [comment]
Please check out https://github.com/fablabnbg/inkscape-centerline-trace/releases/tag/v0.5
